### ISSUE TITLE
Client occasionally crashes on first shot fired

### ISSUE THREAD

**Issue by neothermic** [braidstag/arduino-milestag#18]
Traceback attached, note this has only so far been witnessed on a test rig with trigger electronics ONLY. Feel free to bin it if that's the only reason (though let me know the cause!)

```
Traceback (most recent call last):
  File "/home/pi/game/game/client.py", line 199, in <module>
    main = Main()
  File "/home/pi/game/game/client.py", line 131, in __init__
    self.connectToArduino()
  File "/home/pi/game/game/client.py", line 193, in connectToArduino
    raise RuntimeError("incorrect ack to ClientConnect(): %s" % (line))
RuntimeError: incorrect ack to ClientConnect(): Shot(UnknownSM(0))

Exception in thread Client/Server Read Thread (most likely raised during interpr                       eter shutdown):Exception in thread Client/Server Write Thread (most likely raise                       d during interpreter shutdown):
Traceback (most recent call last):

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "                       /usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/home/pi/game/game/connection.py", line 99, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'
  File "/home/pi/game/game/connection.py", line 158, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

```

**Comment by neothermic** [comment]
Fixed by f56dc04ee4531dc2e0558c95978a4321d7994426
